# Site settings
title: Time is relative
email: arangradient at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  I write about software and science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arandr.github.io" # the base hostname & protocol for your site
github_username:  arandr

# Build settings
markdown: kramdown
encoding: "UTF-8"